/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'robert' at '3/6/14 9:02 PM' with Gradle 1.11
 *
 * @author robert, @date 3/6/14 9:02 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
